-- MySQL Script generated by MySQL Workbench
-- Tue Jan 20 23:22:11 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_digitalizacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_digitalizacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_digitalizacao` DEFAULT CHARACTER SET utf8 COLLATE utf8_swedish_ci ;
USE `db_digitalizacao` ;

-- -----------------------------------------------------
-- Table `db_digitalizacao`.`tb_se`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_digitalizacao`.`tb_se` (
  `sigla_se` VARCHAR(6) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`sigla_se`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `db_digitalizacao`.`tb_gestor_ar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_digitalizacao`.`tb_gestor_ar` (
  `id_gestor_ar` INT(5) NOT NULL,
  `nome` VARCHAR(250) NOT NULL,
  `sigla_se` VARCHAR(5) NOT NULL,
  `unidade` VARCHAR(150) NOT NULL,
  `logradouro` VARCHAR(250) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cep` INT(8) NOT NULL,
  PRIMARY KEY (`id_gestor_ar`),
  INDEX `fk_tb_gestor_ar_tb_se1_idx` (`sigla_se` ASC),
  CONSTRAINT `fk_tb_gestor_ar_tb_se1`
    FOREIGN KEY (`sigla_se`)
    REFERENCES `db_digitalizacao`.`tb_se` (`sigla_se`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `db_digitalizacao`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_digitalizacao`.`tb_cliente` (
  `sigla_cliente` VARCHAR(3) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `sigla_se` VARCHAR(5) NOT NULL,
  `codigo_cliente` INT(7) NOT NULL,
  `armazenamento` VARCHAR(3) NOT NULL,
  `prazo_armazenamento` INT(3) NOT NULL,
  `fragmentar` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`sigla_cliente`),
  INDEX `fk_tb_cliente_tb_se1_idx` (`sigla_se` ASC),
  CONSTRAINT `fk_tb_cliente_tb_se1`
    FOREIGN KEY (`sigla_se`)
    REFERENCES `db_digitalizacao`.`tb_se` (`sigla_se`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `db_digitalizacao`.`tb_armazenamento_ar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_digitalizacao`.`tb_armazenamento_ar` (
  `numero_caixa` INT(5) NOT NULL,
  `data_digitalizacao` DATE NOT NULL,
  `sigla_cliente` VARCHAR(3) NOT NULL,
  `lote_producao_inicial` INT(9) NOT NULL,
  `lote_producao_final` INT(9) NOT NULL,
  `lote_cliente_inicial` INT(9) NOT NULL,
  `lote_cliente_final` INT(9) NOT NULL,
  `quantidade_lotes` INT(4) NOT NULL,
  `quantidade_objetos` INT(4) NOT NULL,
  `localizacao_estante` VARCHAR(45) NOT NULL,
  `data_expurgo` DATE NOT NULL,
  `sigla_se_cliente` VARCHAR(5) NOT NULL,
  `situacao` VARCHAR(45) NOT NULL,
  `data_conferencia` DATE NULL,
  `gerar_etiqueta` VARCHAR(3) NOT NULL DEFAULT 'NÃO',
  `carta_gerada` VARCHAR(3) NOT NULL DEFAULT 'NÃO',
  `sigla_se_armazenamento` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`numero_caixa`),
  INDEX `fk_tb_armazenamento_ar_tb_cliente1_idx` (`sigla_cliente` ASC),
  INDEX `fk_tb_armazenamento_ar_tb_se1_idx` (`sigla_se_cliente` ASC),
  INDEX `fk_tb_armazenamento_ar_tb_se2_idx` (`sigla_se_armazenamento` ASC),
  CONSTRAINT `fk_tb_armazenamento_ar_tb_cliente1`
    FOREIGN KEY (`sigla_cliente`)
    REFERENCES `db_digitalizacao`.`tb_cliente` (`sigla_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_armazenamento_ar_tb_se1`
    FOREIGN KEY (`sigla_se_cliente`)
    REFERENCES `db_digitalizacao`.`tb_se` (`sigla_se`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_armazenamento_ar_tb_se2`
    FOREIGN KEY (`sigla_se_armazenamento`)
    REFERENCES `db_digitalizacao`.`tb_se` (`sigla_se`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `db_digitalizacao`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_digitalizacao`.`tb_usuario` (
  `matricula` INT(8) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `sigla_se` VARCHAR(5) NOT NULL,
  `senha` VARCHAR(250) NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`matricula`),
  INDEX `fk_tb_usuario_tb_se1_idx` (`sigla_se` ASC),
  CONSTRAINT `fk_tb_usuario_tb_se1`
    FOREIGN KEY (`sigla_se`)
    REFERENCES `db_digitalizacao`.`tb_se` (`sigla_se`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
